server:
  port: 8088  #  项目运行端口配置
  servlet:
    context-path: /api
spring:
  application:
    name: demo
  thymeleaf:
    check-template: false
    check-template-location: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   #  数据库链接配置
    name: mysql
    url: jdbc:mysql://127.0.0.1:3306/study
    username: root
    password: root
  redis:
    host: localhost    #   redis配置
    port: 6379
logging:
  config: classpath:logback/logback-spring.xml    #   全局日志配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml     #  mybatis-plus全局配置
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.example.demo
app:     #   定时任务配置
  executor-config:
    core-pool-size: 5    #  核心线程数
    max-pool-size: 10    #  最大线程数
    queue-capacity: 10   #  任务队列容量（阻塞队列）
    keep-alive-time: 60  #  线程空闲时间
  task-query: 1 * * * * ?   # 定时60秒执行一次